version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - app
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      - app
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    image: auth-service
    container_name: auth-service
    networks:
      - app
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8081
      PUBLIC_KEY_PATH: /app/keys/public.pem
      PRIVATE_KEY_PATH: /app/keys/private.pem

      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB_NAME: postgres
      APP_ENV: production
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8081:8081"
  user-service:
    image: user-service
    container_name: user-service
    networks:
      - app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      SERVICE_HOST: 0.0.0.0
      SERVICE_PORT: 8082
      APP_ENV: production
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB_NAME: postgres

  chat-service:
    image: chat-service
    container_name: chat-service
    networks:
      - app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8083:8083"
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8083
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB_NAME: postgres
      APP_ENV: production
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_CLUSTER_ID: ZYzYaT-GeneratedClusterID # можно сгенерировать один раз командой: kafka-storage.sh random-uuid

volumes:
  redis-data:
    driver: local
  pgdata:
    driver: local

networks:
  app:
    driver: bridge
